SNID: 50106142
adaptive_grid: true
avoid_non_linearity: false
background_level: 0
band: Y106
bg_gal_flux: 100000.0
check_perfection: false
deltafcn_profile: false
detim: 2
do_rotation: true
do_xshift: true
fetch_SED: false
fit_background: false
make_exact: false
make_initial_guess: true
makecontourGrid: true
method: lsqr
mismatch_seds: false
noise: 0
npoints: 7
pixel: false
roman_path: /hpc/group/cosmology/OpenUniverse2024
single_grid_point: false
size: 19
sn_path: /hpc/group/cosmology/OpenUniverse2024/roman_rubin_cats_v1.1.2_faint/
source_phot_ops: true
spline_grid: false
testnum: 4
turn_grid_off: false
use_real_images: false
use_roman: true
weighting: true
