replaceable_preloads:
  - sample_campari_config.yaml

photometry:
  campari:
    paths:
      roman_path: /hpc/group/cosmology/OpenUniverse2024
      sn_path: /hpc/group/cosmology/OpenUniverse2024/roman_rubin_cats_v1.1.2_faint/
      output_dir: /hpc/home/cfm37/MultiSMP/campari/tests/testdata
      debug_dir: /hpc/home/cfm37/MultiSMP/campari/tests/testdata

    galsim:
      tds_file: /hpc/home/cfm37/MultiSMP/campari/temp_tds.yaml
